SIMULATION_CONFIG = dict()
SIMULATION_CONFIG['cpu'] = False
SIMULATION_CONFIG['model_dir'] = '../checkpoints/model_0'
SIMULATION_CONFIG['max_eval_size'] = 1000
SIMULATION_CONFIG['load_model'] = None
SIMULATION_CONFIG['resume'] = 0
SIMULATION_CONFIG['processes'] = 1
SIMULATION_CONFIG['log_interval'] = 100
SIMULATION_CONFIG['log_name'] = 'model_0.csv'
SIMULATION_CONFIG['train_dataset'] = '../data/vrp/vrp_20_30_train.json'
SIMULATION_CONFIG['val_dataset'] = '../data/vrp/vrp_20_30_val.json'
SIMULATION_CONFIG['test_dataset'] = '../data/vrp/vrp_20_30_test.json'

MODEL_CONFIG = dict()
MODEL_CONFIG['LSTM_hidden_size'] = 512
MODEL_CONFIG['MLP_hidden_size'] = 256
MODEL_CONFIG['param_init'] = 0.1
MODEL_CONFIG['num_LSTM_layers'] = 1
MODEL_CONFIG['seed'] = None
MODEL_CONFIG['num_sample_rewrite_pos'] = 10
MODEL_CONFIG['num_sample_rewrite_op'] = 10
MODEL_CONFIG['max_reduce_steps'] = 50
MODEL_CONFIG['keep_last_n'] = None
MODEL_CONFIG['eval_every_n'] = 100
MODEL_CONFIG['lr'] = 5e-5
MODEL_CONFIG['value_loss_coef'] = 0.01
MODEL_CONFIG['gamma'] = 0.9
MODEL_CONFIG['batch_size'] = 64
MODEL_CONFIG['num_MLP_layers'] = 2
MODEL_CONFIG['embedding_size'] = 7
MODEL_CONFIG['attention_size'] = 16

TRAIN_CONFIG = dict()
# choices=['adam', 'sgd', 'rmsprop']
TRAIN_CONFIG['optimizer'] = 'adam'
TRAIN_CONFIG['lr_decay_steps'] = 500
TRAIN_CONFIG['lr_decay_rate'] = 0.9
TRAIN_CONFIG['gradient_clip'] = 5.0
TRAIN_CONFIG['num_epochs'] = 10
TRAIN_CONFIG['dropout_rate'] = 0.0
TRAIN_CONFIG['train_proportion'] = 1.0

OUTPUT_CONFIG = dict()
# choices=['succeed', 'fail', 'complete', 'nop']
OUTPUT_CONFIG['output_trace_flag'] = 'nop'
# choices=['pred', 'both']
OUTPUT_CONFIG['output_trace_option'] = 'both'
OUTPUT_CONFIG['output_trace_file'] = None